services:
  authorization-service:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PORT=${PORT}
      - OIDC_ISSUERS=${OIDC_ISSUERS}
      - OIDC_AUDIENCES=${OIDC_AUDIENCES}
    # Mount local configs (drop policies.yaml here)
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped
