version: '3.8'

services:
  authorization-service:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped
