version: '3.8'

services:
  authorization-service:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped
