{{- if or .Values.oidc.clientID .Values.oidc.clientSecret .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authorization-service.fullname" . }}
type: Opaque
stringData:
  {{- if .Values.oidc.clientID }}
  CLIENT_ID: {{ .Values.oidc.clientID | quote }}
  {{- end }}
  {{- if .Values.oidc.clientSecret }}
  CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
