identity:
  issuer: "https://idp.example.com/realms/main"
  jwks_url: "https://idp.example.com/realms/main/protocol/openid-connect/certs"
  audience: "authorization-service"
  claims:
    subject: "sub"
    username: "preferred_username"
    tenant: "tenant"
    roles:
      - "realm_access.roles"
      - "resource_access.authorization-service.roles"
    strip_prefix: ""
server:
  addr: ":8080"
  log_level: "info"
