roles:
  - name: "admin"
    policies:
      - "policy1"
      - "policy2"
  - name: "editor"
    policies:
      - "policy3"
      - "policy4"

users:
  - username: "user1"
    roles: ["admin"]
  - username: "user2"
    roles: ["editor"]

policies:
  - id: "policy1"
    description: "Allow admin to read any file"
    subjects: 
      - role: "admin"
    resource: 
      - "*"
    action: 
      - "read"
    effect: "allow"

  - id: "policy2"
    description: "Allow admin to write any file"
    subjects: 
      - role: "admin"
    resource: 
      - "*"
    action: 
      - "write"
    effect: "allow"

  - id: "policy3"
    description: "Allow editor to read any file"
    subjects: 
      - role: "editor"
    resource: 
      - "*"
    action: 
      - "read"
    effect: "allow"

  - id: "policy4"
    description: "Allow editor to edit own files"
    subjects: 
      - role: "editor"
    resource: 
      - "file2"
    action: 
      - "edit"
    effect: "allow"
