name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 5m --issues-exit-code=0

      - name: Test
        run: |
          go list ./... | grep -v tests/integration | grep -v github.com/bradtumy/authorization-service/api | xargs go test

      - name: Integration Tests
        env:
          POLICY_FILE: ${{ github.workspace }}/configs/policies.yaml
        run: go test ./tests/integration
